# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: dfbcafbb222daaaf3cb72e2fbb9f21f5c8c498409357464fd78c1cc2f4eb3e9cfdb1d956350486016111bd1b78b2602b48330d1b976fa6e7d2f40c24412be0c2

test:
  secret_key_base: cec7c0ba1d9ff8db397a662ad38f46c0029ad98ada62220c899f4b8f9d93c3960adae142811c69e1fff2a07211952a5dd96acb23207f1e725dbcc5a5adaffd70

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: 31918560e90b822376d18c6d6807b3b4546854c6beee6570343983b424db0ada5f92300dd250964f12af38192372730de41fb24a2b52c5fa1c4405ced24b20d6
